services:
  db:
    container_name: kahinabase
    image: mysql:latest
    volumes:
      - ./restaurant.sql:/docker-entrypoint-initdb.d/restaurant.sql
    environment:
      MYSQL_ROOT_PASSWORD: kahina
      MYSQL_DATABASE: restaurant
      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306"

  web:
    build:
      context: .
      container_name: kahinaweb
      dockerfile: Dockerfile
    image: applirestau
    ports:
      - "${PORT}:80"
    depends_on:
      - db
